version: '3.8'
services:
  web:
    container_name: mynextapp
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
